locale: 'en'

media_folder: "static/medias/uploads"
public_folder: "/medias/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    format: "json"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "lib/Post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: "post_list"
    label: "Post List"
    folder: "content/post_list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    format: "json"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "lib/components/PostList" }
      - { label: "Name", name: "title", widget: "string", default: List }
      - { label: "Posts", name: "list", widget: "relation", multiple: true, collection: "post", value_field: "{{slug}}", search_fields: ["title"] }
  - name: pages
    label: Pages
    files:
    - name: home
      label: Home
      file: content/pages/home.json
      fields:
        - { label: Layout, name: layout, widget: hidden, default: lib/pages/Home }
        - { label: Title, name: title, widget: string, default: Home }
        - name: postChild
          label: Post data within Home
          widget: object
          collapsed: true
          collection: post
        - { label: Post List as a relation, name: postListRelation, widget: relation, collection: post_list, value_field: "{{slug}}", search_fields: ["title"] }
