locale: 'en'

media_folder: "static/medias/uploads"
public_folder: "/medias/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    format: "json"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "lib/Post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    files:
    - name: home
      label: Home
      file: content/pages/home.json
      fields:
        - { label: Layout, name: layout, widget: hidden, default: lib/pages/Home }
        - { label: Title, name: title, widget: string, default: Home }
        - name: post
          label: Post
          widget: object
          collapsed: true
          collection: post
